### ISSUE TITLE
How to disable redmine_omniauth_saml? 

### ISSUE THREAD

**Issue by kpolucas** [chrodriguez/redmine_omniauth_saml#11]
The plugin works like a charm.
I know is not an issue but. Do you know how to disable it for a while?
i tried with 
`rake redmine:plugins:migrate NAME=redmine_omniauth_sam VERSION=0 RAILS_ENV=production`
but nothing happen
(redmine 3.0)

**Comment by kpolucas** [comment]
It works after removing config/initializers/saml.rb 
sorry to bother

**Comment by chrodriguez** [comment]
Hi! thanks for your post. I've checked that accessing redmine_ominauth_saml settings page, accesed by /settings/plugin/redmine_omniauth_saml, you can disable this plugin

**Comment by kpolucas** [comment]
The IDP was down, so i couldn't bypass the login.
Also, i suck on ruby
Sorry again.
