### ISSUE TITLE
WARNING: Can't mass-assign protected attributes for User: login  

### ISSUE THREAD

**Issue by acosonic** [chrodriguez/redmine_omniauth_saml#23]
Trying to get oneLogin to work, and keep getting

```
WARNING: Can't mass-assign protected attributes for User: login
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Completed 422 Unprocessable Entity in 11ms (ActiveRecord: 1.6ms)

ActiveRecord::RecordInvalid (Validation failed: Login cannot be blank):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by acosonic** [comment]
That's for new account creation, apparently in user patch

this line
`user = new user_attributes`

tries to assign multiple protected attributes, including mail, and login seems blank.

I'm not sure mail can even be assigned that way.

**Comment by acosonic** [comment]
I actually have fixed this in my fork, but made it onelogin specific...

**Comment by chrodriguez** [comment]
I've seen your PR. If you fix the comments I've made, I'll merge it

Thanks!!
