### ISSUE TITLE
Unable to configure Redmine Omniauth SAML plugin

### ISSUE THREAD

**Issue by markwintch** [chrodriguez/redmine_omniauth_saml#27]
In my Redmine application, whenever I click configure I get a 404 error: The page you were trying to access doesn't exist or has been removed.

On your install instructions you state: "**Finaly you need to configure some minor options for the plugin to work, in “Administration” > “Plugins” > “Configure” on the OmniAuth SAML plugin line.**"

Should I be doing this from a command prompt rather than the GUI of the application.  If possible, I need clear instructions please.

  Redmine version                2.6.5.stable
  Ruby version                   2.1.6-p336 (2015-04-13) [x64-mingw32]
  Rails version                  3.2.21
  redmine_omniauth_saml          0.0.1

Running on Windows Server 2012

**Comment by chrodriguez** [comment]
I think smething is broken with your installation. Can you upload your logs?

**Comment by markwintch** [comment]
Here is the production log.  If you need other please let me know.  Thank you for your assistance.
Production log:
*****************************************************************************************************
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:11:33 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 156.3ms (ActiveRecord: 46.9ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:11:49 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 265.6ms (Views: 46.9ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:12:00 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:12:00 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 0.0ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:12:10 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:12:10 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 15.6ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:12:20 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:12:20 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 0.0ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:12:30 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:12:30 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 0.0ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:12:40 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:12:40 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.University.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (15.6ms)
Completed 404 Not Found in 15.6ms (Views: 15.6ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:12:50 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:12:50 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 15.6ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-05-03 02:13:01 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev.UNIVERSITY.com/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev.UNIVERSITY.com%2Fredmine%2F" for 127.0.0.1 at 2017-05-03 02:13:01 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev.UNIVERSITY.com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 15.6ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 08:17:34 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 250.0ms (Views: 31.3ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 08:59:28 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 281.3ms (Views: 31.3ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 08:59:45 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 0.0ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 09:12:58 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 250.0ms (Views: 46.9ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 09:15:13 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 250.0ms (Views: 31.3ms | ActiveRecord: 0.0ms)
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 09:17:48 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 0.0ms | ActiveRecord: 0.0ms)
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 09:17:52 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 15.6ms (Views: 0.0ms | ActiveRecord: 0.0ms)
*********************************************************************************************************

**Comment by vijaykotha** [comment]
Hi chrodriguez,

I am also getting same error on login page.
In the production.log I found this

Started GET "/redmine/login" for 127.0.0.1 at 2017-05-03 09:15:13 -0500
Processing by AccountController#login as HTML
Current user: anonymous
Rendered account/login.html.erb within layouts/base (15.6ms)
Missing template, responding with 404
Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 250.0ms (Views: 31.3ms | ActiveRecord: 0.0ms)

Please help me out

**Comment by chrodriguez** [comment]
Hi @markwintch, as I can see in your first email, you are using this plugin with redmine 2.x? If this is your case, please consider upgrading Redmine, because this plugin works with redmine 3.0 or higher

**Comment by markwintch** [comment]
I was under the impression that there is a branch for Redmine 2.0 as well as 3.0. I was working under the 2.0 branch, is that code not working?

I also realized, the log I gave you was probably not much help except for perhaps the issue we have not getting logged in currently.  I believe that is because we do not have the correct SSL fingerprint.  Anyhow, here is the log file from when I removed the plugin and was able to get logged in, throughout the install of the plugin and then to the point where I am now of no longer being able to login to the application.  

I do not want to lose sight of the original reason for this thread however.  Prior to not being able to get logged in.  At the point when I had first installed the plugin, but not signed out.  I did restart Redmine, but was able to login and when I went to Administration--->Settings----->Plugins---->Omniauth SAML and selected Configure I got a page can't be found error.  Hopefully this log file will help you help me, or if in fact this plugin is not compatible with Redmine 2.6.5 then we will pursue other options.

Thank you for your assistance.

Redirected to http://redminedev..com/redmine/login?back_url=http%3A%2F%2Fredminedev..com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev..com%2Fredmine%2F" for 127.0.0.1 at 2017-04-19 02:03:42 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev..com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Completed 200 OK in 0.0ms (Views: 0.0ms | ActiveRecord: 0.0ms)
Started GET "/redmine" for 127.0.0.1 at 2017-04-19 02:03:53 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redminedev..com/redmine/login?back_url=http%3A%2F%2Fredminedev..com%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 0.0ms (ActiveRecord: 0.0ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Fredminedev..com%2Fredmine%2F" for 127.0.0.1 at 2017-04-19 02:03:53 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redminedev..com/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (0.0ms)
Completed 200 OK in 15.6ms (Views: 15.6ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login" for 127.0.0.1 at 2017-05-01 15:36:27 -0500
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (62.5ms)
Completed 200 OK in 218.8ms (Views: 125.0ms | ActiveRecord: 31.3ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine" for [::1]:63668 at 2017-05-01 15:38:23 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://localhost/redmine/login?back_url=http%3A%2F%2Flocalhost%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 78.1ms (ActiveRecord: 15.6ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login?back_url=http%3A%2F%2Flocalhost%2Fredmine%2F" for [::1]:63668 at 2017-05-01 15:38:39 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://localhost/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (46.9ms)
Completed 200 OK in 171.9ms (Views: 93.8ms | ActiveRecord: 15.6ms)
Started POST "/redmine/login" for [::1]:63667 at 2017-05-01 15:38:55 -0500
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"0+LVcKCNYDafzLyMftw49U+1OF260AiHFQITM2enKxI=", "back_url"=>"http://localhost/redmine/", "username"=>"G00137348", "password"=>"[FILTERED]", "login"=>"Login »"}
  Current user: anonymous
Successful authentication for 'G00137348' from [::1]:63667 at 2017-05-01 20:38:55 UTC
Redirected to http://localhost/redmine/
Completed 302 Found in 78.1ms (ActiveRecord: 62.5ms)
Started GET "/redmine/" for [::1]:63667 at 2017-05-01 15:38:55 -0500
Processing by WelcomeController#index as HTML
  Current user: G00137348 (id=2293)
  Rendered news/_news.html.erb (31.3ms)
  Rendered welcome/index.html.erb within layouts/base (171.9ms)
Completed 200 OK in 468.8ms (Views: 234.4ms | ActiveRecord: 140.7ms)
Started POST "/redmine/login" for 127.0.0.1 at 2017-05-01 16:01:53 -0500
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"DQirihVF8sBLj+e+A8hFnPfeB4W5gmURnU0EdMuXuZM=", "back_url"=>"http://redmine..dev/redmine/login?back_url=http://redmine..dev/redmine/", "username"=>"G00137348", "password"=>"[FILTERED]", "login"=>"Login »"}
  Current user: anonymous
Successful authentication for 'G00137348' from 127.0.0.1 at 2017-05-01 21:01:53 UTC
Redirected to http://redmine..dev/redmine/my/page
Completed 302 Found in 15.6ms (ActiveRecord: 15.6ms)
Started GET "/redmine/my/page" for 127.0.0.1 at 2017-05-01 16:01:53 -0500
Processing by MyController#page as HTML
  Current user: G00137348 (id=2293)
  Rendered issues/_list_simple.html.erb (93.8ms)
  Rendered my/blocks/_issueswatched.html.erb (375.0ms)
  Rendered news/_news.html.erb (0.0ms)
  Rendered my/blocks/_news.html.erb (62.5ms)
  Rendered my/blocks/_timelog.html.erb (31.3ms)
  Rendered issues/_list_simple.html.erb (31.3ms)
  Rendered my/blocks/_issuesassignedtome.html.erb (187.5ms)
  Rendered my/page.html.erb within layouts/base (687.5ms)
Completed 200 OK in 734.4ms (Views: 234.3ms | ActiveRecord: 500.1ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/" for 127.0.0.1 at 2017-05-02 09:13:10 -0500
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://redmine..dev/redmine/login?back_url=http%3A%2F%2Fredmine..dev%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 93.8ms (ActiveRecord: 31.3ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/login?back_url=http%3A%2F%2Fredmine..dev%2Fredmine%2F" for 127.0.0.1 at 2017-05-02 09:13:27 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://redmine..dev/redmine/"}
Started GET "/redmine/" for [::1]:58164 at 2017-05-02 09:13:27 -0500
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (62.6ms)
Processing by WelcomeController#index as HTML
Completed 200 OK in 172.0ms (Views: 156.4ms | ActiveRecord: 0.0ms)
  Current user: anonymous
Redirected to http://localhost/redmine/login?back_url=http%3A%2F%2Flocalhost%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 93.8ms (ActiveRecord: 15.6ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Flocalhost%2Fredmine%2F" for [::1]:58164 at 2017-05-02 09:13:27 -0500
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://localhost/redmine/"}
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (46.9ms)
Completed 200 OK in 109.5ms (Views: 93.8ms | ActiveRecord: 15.6ms)
Started POST "/redmine/login" for 127.0.0.1 at 2017-05-02 09:20:15 -0500
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"dMdtQZs3PWptPs3OzgXiZg7aeXFMaWDF/CclRoY9SDg=", "back_url"=>"http://redmine..dev/redmine/", "username"=>"G00137348", "password"=>"[FILTERED]", "login"=>"Login »"}
CONNECTION RETRY: ActiveRecord::ConnectionAdapters::SQLServerAdapter retry #0.
  Current user: anonymous
Successful authentication for 'G00137348' from 127.0.0.1 at 2017-05-02 14:20:15 UTC
Redirected to http://redmine..dev/redmine/
Completed 302 Found in 46.9ms (ActiveRecord: 15.6ms)
Started GET "/redmine/" for 127.0.0.1 at 2017-05-02 09:20:15 -0500
Processing by WelcomeController#index as HTML
CONNECTION RETRY: ActiveRecord::ConnectionAdapters::SQLServerAdapter retry #0.
  Current user: G00137348 (id=2293)
  Rendered news/_news.html.erb (31.3ms)
  Rendered welcome/index.html.erb within layouts/base (234.4ms)
Completed 200 OK in 562.7ms (Views: 140.6ms | ActiveRecord: 328.3ms)
Started GET "/redmine/admin" for 127.0.0.1 at 2017-05-02 09:20:24 -0500
Processing by AdminController#index as HTML
  Current user: G00137348 (id=2293)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered admin/index.html.erb within layouts/admin (15.6ms)
  Rendered layouts/base.html.erb (109.4ms)
Completed 200 OK in 171.9ms (Views: 140.7ms | ActiveRecord: 0.0ms)
Started GET "/redmine/admin/info" for 127.0.0.1 at 2017-05-02 09:20:26 -0500
Processing by AdminController#info as HTML
  Current user: G00137348 (id=2293)
Imagemagick's convert binary (convert) not available
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby21-x64\bin)
You can configure your scm commands in config/configuration.yml.
"svn" --version
with: No such file or directory - "svn" --version
scm: error during get scm available: No such file or directory - "svn" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby21-x64\bin)
You can configure your scm commands in config/configuration.yml.
"darcs" --version
with: No such file or directory - "darcs" --version
scm: error during get scm available: No such file or directory - "darcs" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby21-x64\bin)
You can configure your scm commands in config/configuration.yml.
"hg" --version
with: No such file or directory - "hg" --version
scm: error during get scm available: No such file or directory - "hg" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby21-x64\bin)
You can configure your scm commands in config/configuration.yml.
"cvs" --version
with: No such file or directory - "cvs" --version
scm: error during get scm available: No such file or directory - "cvs" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby21-x64\bin)
You can configure your scm commands in config/configuration.yml.
"bzr" --version
with: No such file or directory - "bzr" --version
scm: error during get scm available: No such file or directory - "bzr" --version
SCM command failed, make sure that your SCM command (e.g. svn) is in PATH (C:/Ruby21-x64/lib/ruby/gems/2.1.0/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Ruby21-x64\bin)
You can configure your scm commands in config/configuration.yml.
"git" --version --no-color
with: No such file or directory - "git" --version --no-color
scm: error during get scm available: No such file or directory - "git" --version --no-color
  Rendered admin/info.html.erb within layouts/admin (15.6ms)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered layouts/base.html.erb (15.6ms)
Completed 200 OK in 109.4ms (Views: 62.5ms | ActiveRecord: 0.0ms)
Started GET "/redmine/admin" for 127.0.0.1 at 2017-05-02 09:20:30 -0500
Processing by AdminController#index as HTML
  Current user: G00137348 (id=2293)
  Rendered admin/_menu.html.erb (0.0ms)
  Rendered admin/index.html.erb within layouts/admin (0.0ms)
  Rendered layouts/base.html.erb (31.3ms)
Completed 200 OK in 46.9ms (Views: 31.3ms | ActiveRecord: 15.6ms)
Started GET "/redmine/admin/plugins" for 127.0.0.1 at 2017-05-02 09:20:32 -0500
Processing by AdminController#plugins as HTML
  Current user: G00137348 (id=2293)
  Rendered admin/plugins.html.erb within layouts/admin (0.0ms)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered layouts/base.html.erb (31.3ms)
Completed 200 OK in 62.5ms (Views: 46.9ms | ActiveRecord: 0.0ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Migrating to CreateIssueStatusOrders (1)
Migrating to CreateAgileColors (2)
Migrating to RenameIssueStatusOrders (3)
Migrating to RenameAgileRanks (4)
Migrating to AddStoryPointsToAgileRanks (5)
Migrating to CreateRichRichImages (20130418001207)
Migrating to AddUriCacheToRichImage (20130418001208)
Migrating to RefactorImageToFile (20130418001209)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/admin/plugins" for 127.0.0.1 at 2017-05-02 10:15:07 -0500
Processing by AdminController#plugins as HTML
  Current user: G00137348 (id=2293)
  Rendered admin/plugins.html.erb within layouts/admin (46.9ms)
  Rendered admin/_menu.html.erb (15.6ms)
  Rendered layouts/base.html.erb (203.1ms)
Completed 200 OK in 421.9ms (Views: 218.7ms | ActiveRecord: 78.2ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/settings/plugin/redmine_omniauth_saml" for 127.0.0.1 at 2017-05-02 10:15:24 -0500
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_omniauth_saml"}
  Current user: G00137348 (id=2293)
  Rendered settings/plugin.html.erb within layouts/admin (0.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
Completed 404 Not Found in 109.4ms (Views: 46.9ms | ActiveRecord: 31.3ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/admin/plugins" for 127.0.0.1 at 2017-05-02 10:20:43 -0500
Processing by AdminController#plugins as HTML
  Current user: G00137348 (id=2293)
  Rendered admin/plugins.html.erb within layouts/admin (46.9ms)
  Rendered admin/_menu.html.erb (0.0ms)
  Rendered layouts/base.html.erb (171.9ms)
Completed 200 OK in 406.3ms (Views: 218.8ms | ActiveRecord: 78.2ms)
Connecting to database specified by database.yml
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
Started GET "/redmine/settings/plugin/redmine_omniauth_saml" for 127.0.0.1 at 2017-05-02 10:21:00 -0500
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_omniauth_saml"}
  Current user: G00137348 (id=2293)
  Rendered settings/plugin.html.erb within layouts/admin (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)

**Comment by markwintch** [comment]
I installed the plugin on Redmine 3.3.2 and did not have the problem with the configuration page showing.
