### ISSUE TITLE
For use Bitnami 3.0.3

### ISSUE THREAD

**Issue by yoshito0504** [chrodriguez/redmine_omniauth_saml#3]
I had to some modify code or files for using Bitnami 3.0.3 Redmine.

■Modify Gemfile & Gemfile.lock
1st
Copy contents of  Plugins-Gemfile & Gemfile.lock to Bitnami Gemfile&Gem.lock
Copy contents to : /opt/bitnami/apps/redmine/htdocs/Gemfile
2nd
Remove Gemfile & Gem.lock from plugin.
3rd
on "/opt/bitnami/apps/redmine/htdocs" @bundle@

■Rename Plugins folder name as same as init.rb
Change plugin folder name from "redmine_omniauth_saml-master" to "redmine_omniauth_saml"
because We may use same name as plugins folder name and defined name by plugins init.rb 

■saml.rb
When finished moving file "saml.rb" from plugin to "opt/bitnami/apps/redmine/htdoc/config/initializers", may remove saml.rb from plugins

**Comment by chrodriguez** [comment]
Hi @yoshito0504 ! So I understand that you can install this plugin following those steps. Do you?

Thanks

**Comment by yoshito0504** [comment]
Hi @chrodriguez  Yes, I can install this plugin following steps I wrote. My purpose is other Bitnami user easly install this plugin.

**Comment by fontanon** [comment]
@yoshito0504 did you get redmine working with redmine_omniauth_saml finally? 

I was able to install the plugin (redmine_omniauth_saml-master with redmine 2.5.3-stable) but it always redirects to a 404 when login.

**Comment by chrodriguez** [comment]
@fontanon are you configuring the right endpoints. Take a look at https://github.com/chrodriguez/redmine_omniauth_saml/blob/master/sample-saml-initializers.rb to get a sample configuration initializer

**Comment by fontanon** [comment]
Hi @chrodriguez ! Thanks for your advice! However, I think my saml.rb file is well configured, would you please have a look? As I'm using redmine 2.5.3-stable my saml.rb file is based on the following sample configuration initialized: https://github.com/chrodriguez/redmine_omniauth_saml/blob/redmine-2.0/sample-saml-initializers.rb

```ruby
# Edit the options depending on your SAML needs
RedmineSAML = HashWithIndifferentAccess.new(
    :assertion_consumer_service_url => "http://redmine.podsystem.com", # The redmine application hostname
    :issuer                         => "podsystem",   # The issuer name
    :idp_sso_target_url             => "https://podsystem.onelogin.com/trust/saml2/http-post/sso/PRIVATE", # SSO login endpoint
    :idp_cert_fingerprint           => ""PR:IV:AT:EX:FI:NG:ER:PR:IN:TX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"", # SSL fingerprint
    :name_identifier_format         => "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
    :logout_admin                   => "https://podsystem.onelogin.com/trust/saml2/http-redirect/slo/PRIVATE", # SSO logout URL
    :attribute_mapping              => { 
    # How will we map attributes from SSO to redmine attributes
      :login      => 'extra.raw_info.username',
      :firstname  => 'extra.raw_info.first_name',
      :lastname   => 'extra.raw_info.last_name',
      :mail       => 'extra.raw_info.personal_email'
    }
)

# The following code must be present. Don't remove it
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :saml, RedmineSAML
end
```

**Comment by chrodriguez** [comment]
Are you seeing this 404 error in Redmine? or in your IDP? May be using the Network Panel In The Chrome Developer Tools can help detecting which server is returning 404...

Did you run bundle after installing this plugin? Because it installs new dependencies

**Comment by fontanon** [comment]
Hi @chrodriguez thanks again for your help :)

Yes, I've run `bundle install` and the following dependencies were installed:
```
Using omniauth 1.3.1
Using ruby-saml 0.7.2
Using omniauth-saml 1.0.0
```

Maybe this helps: after installing the plugin with the configuration set on my last comment (`saml.rb` file), a "Login with Single-Sign On" button appears on redmine's login page (http://redmine.podsystem.com/login). When I click on that button it is redirected to the following non existing page (with a 404):

http://redmine.podsystem.com/auth/saml?origin=http%3A%2F%2Fredmine.podsystem.com%2F

For me is weird the origin being the URL same as the consumer. Shouldn't it be the IDP target url instead?

**Comment by chrodriguez** [comment]
Oh! I've realized that you are using Redmine 2.5. Did you install master branch of this plugin? If that is the case, it might not work because of the rails routing syntax

As you can see *[2.x](https://github.com/chrodriguez/redmine_omniauth_saml/blob/redmine-2.0/config/routes.rb)*:
```ruby
RedmineApp::Application.routes.draw do
  match 'auth/failure', :to => 'account#login_with_saml_failure'
  match 'auth/:provider/callback', :to => 'account#login_with_saml_callback'
  match 'auth/:provider', :to => 'account#login_with_saml_redirect'
end
``` 

differs from *[Master](https://github.com/chrodriguez/redmine_omniauth_saml/blob/master/config/routes.rb)*:
```ruby
RedmineApp::Application.routes.draw do
  match '/auth/failure'             => 'account#login_with_saml_failure',   via: [:get, :post]
  match '/auth/:provider/callback'  => 'account#login_with_saml_callback',  via: [:get, :post]
  match '/auth/:provider'           => 'account#login_with_saml_redirect',  as: :sign_in, via: [:get, :post]
end
```
Try downloading: https://github.com/chrodriguez/redmine_omniauth_saml/tree/redmine-2.0 instead and give it a try

Hope it helps

**Comment by fontanon** [comment]
@chrodriguez I was using the 2.x branch all the time, I've to say. Have a look at the following screenshot: https://is.gd/SAolQJ

I can't understand why it is redirecting to http://redmine.podsystem.com/auth/saml?origin=http%3A%2F%2Fredmine.podsystem.com%2F ...

**Comment by chrodriguez** [comment]
@fontanon have you solved this issue? I close it. Please reopen if needed
