### ISSUE TITLE
Group synchronization

### ISSUE THREAD

**Issue by Marlinc** [chrodriguez/redmine_omniauth_saml#7]
Is it possible to some how do group synchronization for users. We're currently using LDAP with the https://github.com/thorin/redmine_ldap_sync plugin.

**Comment by chrodriguez** [comment]
Hi @Marlinc! As you can see in https://github.com/chrodriguez/redmine_omniauth_saml/blob/master/sample-saml-initializers.rb

there is a block yo can write with your own code after login so you can manage group synchronization
