### ISSUE TITLE
404 not found (Redmine 3)

### ISSUE THREAD

**Issue by alenkovich** [chrodriguez/redmine_omniauth_saml#8]
Hi!

I'm getting "Not found" error after clicking on "Login with SAML" .. and I'm stuck here.

Can you please give me some directions for debugging further..

Thanks,
Alen

----
Environment:
  Redmine version                3.1.1.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_omniauth_saml          0.0.1

**Comment by michael-bouvy** [comment]
Hi @alenkovich,

Can you tell me what URL generates the 404 error ?

How did you configure your `assertion_consumer_service_url` and `idp_sso_target_url` parameters in the initializers config ?

**Comment by alenkovich** [comment]
Well, it seems that the main problem was my mistake -> I've added saml.rb to plugins config/initializers :/

Anyway, my colleague also added metadata view.. Now it all works :)

Thanks!
